### ISSUE TITLE
Error on pip install

### ISSUE THREAD

**Issue by devleaks** [pyturf/pyturf#47]
First of all, thank you for this port. Turf is a simple great package for geo processing.

I get the following when I try to install:

```
pip install --no-cache-dir pyturf
Collecting pyturf
  Downloading pyturf-0.6.0.tar.gz (36 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/miniconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/setup.py'"'"'; __file__='"'"'/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-pip-egg-info-85im_2as
         cwd: /private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/
    Complete output (34 lines):
    Traceback (most recent call last):
      File "/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/setup.py", line 8, in <module>
        __version__ = os.environ["GITHUB_REF"].split("/")[-1]
      File "/usr/local/miniconda3/lib/python3.7/os.py", line 678, in __getitem__
        raise KeyError(key) from None
    KeyError: 'GITHUB_REF'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/setup.py", line 11, in <module>
        from turf.version import __version__
      File "/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/turf/__init__.py", line 6, in <module>
        from turf.boolean_disjoint import boolean_disjoint
      File "/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/turf/boolean_disjoint/__init__.py", line 1, in <module>
        from turf.boolean_disjoint._boolean_disjoint import boolean_disjoint
      File "/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/turf/boolean_disjoint/_boolean_disjoint.py", line 18, in <module>
        from turf.line_intersect import line_intersect
      File "/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/turf/line_intersect/__init__.py", line 1, in <module>
        from turf.line_intersect._line_intersect import line_intersect
      File "/private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-install-kn0lrqax/pyturf_4a70855c9ede4d46befbd00fa835dc51/turf/line_intersect/_line_intersect.py", line 4, in <module>
        from rtree import index
      File "/usr/local/miniconda3/lib/python3.7/site-packages/rtree/__init__.py", line 9, in <module>
        from .index import Rtree, Index  # noqa
      File "/usr/local/miniconda3/lib/python3.7/site-packages/rtree/index.py", line 6, in <module>
        from . import core
      File "/usr/local/miniconda3/lib/python3.7/site-packages/rtree/core.py", line 77, in <module>
        rt.Error_GetLastErrorNum.restype = ctypes.c_int
      File "/usr/local/miniconda3/lib/python3.7/ctypes/__init__.py", line 369, in __getattr__
        func = self.__getitem__(name)
      File "/usr/local/miniconda3/lib/python3.7/ctypes/__init__.py", line 374, in __getitem__
        func = self._FuncPtr((name_or_ordinal, self))
    AttributeError: dlsym(RTLD_DEFAULT, Error_GetLastErrorNum): symbol not found
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/cc/78/aed4022347342291bb38561ebc7dfc1468f1b625970387a3aacc23734f31/pyturf-0.6.0.tar.gz#sha256=23b3ff2e42105da357416a4c2e92c3573d609d6c91351171612bfed180c49a00 (from https://pypi.org/simple/pyturf/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Downloading pyturf-0.5.0.tar.gz (26 kB)
Requirement already satisfied: numpy in /usr/local/miniconda3/lib/python3.7/site-packages (from pyturf) (1.19.5)
Building wheels for collected packages: pyturf
  Building wheel for pyturf (setup.py) ... done
  Created wheel for pyturf: filename=pyturf-0.5.0-py3-none-any.whl size=39727 sha256=ff99edb80862be517897f0cc87e0e36cb932f724245c1db932cd8c5e75114b88
  Stored in directory: /private/var/folders/jb/pflpzw4d0h75qsrd23z_t_0r0000gn/T/pip-ephem-wheel-cache-xkq8xcsk/wheels/d6/6a/2f/86f0c8ed86354a669c0b26944fd744b5f5e4fa0af134312c56
Successfully built pyturf
Installing collected packages: pyturf
Successfully installed pyturf-0.5.0
```

On another environment, it installed OK but I had to install required packages (numpy and rtree) manually before pip could go through.

Best regards

Pierre

**Comment by SteffenHaeussler** [comment]
Thanks, I will have a look.

**Comment by baditaflorin** [comment]
I have the same issue. MacOs M1 

```
Collecting pyturf==0.6.2
  Using cached pyturf-0.6.2.tar.gz (36 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-install-2p137s4u/pyturf_a220078a7cba4d4cbda8a548c661cb04/setup.py", line 8, in <module>
          __version__ = os.environ["GITHUB_REF"].split("/")[-1]
        File "/opt/homebrew/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/os.py", line 680, in __getitem__
          raise KeyError(key) from None
      KeyError: 'GITHUB_REF'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-install-2p137s4u/pyturf_a220078a7cba4d4cbda8a548c661cb04/setup.py", line 11, in <module>
          from turf.version import __version__
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-install-2p137s4u/pyturf_a220078a7cba4d4cbda8a548c661cb04/turf/__init__.py", line 6, in <module>
          from turf.boolean_disjoint import boolean_disjoint
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-install-2p137s4u/pyturf_a220078a7cba4d4cbda8a548c661cb04/turf/boolean_disjoint/__init__.py", line 1, in <module>
          from turf.boolean_disjoint._boolean_disjoint import boolean_disjoint
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-install-2p137s4u/pyturf_a220078a7cba4d4cbda8a548c661cb04/turf/boolean_disjoint/_boolean_disjoint.py", line 18, in <module>
          from turf.line_intersect import line_intersect
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-install-2p137s4u/pyturf_a220078a7cba4d4cbda8a548c661cb04/turf/line_intersect/__init__.py", line 1, in <module>
          from turf.line_intersect._line_intersect import line_intersect
        File "/private/var/folders/_w/m38196x96cs9ptvv1j0srlp80000gp/T/pip-install-2p137s4u/pyturf_a220078a7cba4d4cbda8a548c661cb04/turf/line_intersect/_line_intersect.py", line 4, in <module>
          from rtree import index
      ModuleNotFoundError: No module named 'rtree'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by baditaflorin** [comment]
If I add GITHUB_REF I get another error

```
export GITHUB_REF=refs/heads/main

pip install pyturf==0.6.2

Collecting pyturf==0.6.2
  Using cached pyturf-0.6.2.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
  WARNING: Requested pyturf==0.6.2 from https://files.pythonhosted.org/packages/7d/25/c591c0ed4f958e8c1ac3b1fd1a94f311f48b54ba869632ee0ea5cac8bbaa/pyturf-0.6.2.tar.gz, but installing version main
Discarding https://files.pythonhosted.org/packages/7d/25/c591c0ed4f958e8c1ac3b1fd1a94f311f48b54ba869632ee0ea5cac8bbaa/pyturf-0.6.2.tar.gz (from https://pypi.org/simple/pyturf/) (requires-python:>=3.5): Requested pyturf==0.6.2 from https://files.pythonhosted.org/packages/7d/25/c591c0ed4f958e8c1ac3b1fd1a94f311f48b54ba869632ee0ea5cac8bbaa/pyturf-0.6.2.tar.gz has inconsistent version: expected '0.6.2', but metadata has 'main'
ERROR: Could not find a version that satisfies the requirement pyturf==0.6.2 (from versions: 0.1, 0.2, 0.3.5, 0.4.0, 0.4.1, 0.4.6, 0.4.7, 0.4.10, 0.4.12, 0.5.0, 0.6.0, 0.6.2)
ERROR: No matching distribution found for pyturf==0.6.2
```

**Comment by SteffenHaeussler** [comment]
Thank you. I will have a look.

**Comment by SteffenHaeussler** [comment]
@baditaflorin @devleaks 

as a quick ugly fix - if you enter
```
pip install rtree
```
it will be possible to install pyturf with e.g.:
```
pip install pyturf==0.6.2
```
