### ISSUE TITLE
PyTurf is failing in Github Actions

### ISSUE THREAD

**Issue by jeafreezy** [pyturf/pyturf#61]
Hi,

Thank you for the great library!

Why does pyturf fails when installing dependencies in my GitHub actions?

runs on - ubuntu-latest
python version: 3.9

See attached screenshot for error message.

![image](https://user-images.githubusercontent.com/36086324/233370640-764b9dec-a96e-4a94-9e30-d7736d0b64ba.png)

**Comment by traitortots** [comment]
I'm getting similar issues when trying to install with pip:
`pip install pyturf`
```
Collecting pyturf
  Using cached pyturf-0.6.3.tar.gz (36 kB)
  Preparing metadata (setup.py) ... done
Discarding https://files.pythonhosted.org/packages/c8/50/9d65453107938808717a979bdc7508bf7acd0a7ddddafcf19394bc5b2708/pyturf-0.6.3.tar.gz#sha256=90100be305a0d59abb540a54fb7cf65112cec589fca5f4647a6e56c13d5a8b0f (from https://pypi.org/simple/pyturf/) (requires-python:>=3.5): Requested pyturf from https://files.pythonhosted.org/packages/c8/50/9d65453107938808717a979bdc7508bf7acd0a7ddddafcf19394bc5b2708/pyturf-0.6.3.tar.gz#sha256=90100be305a0d59abb540a54fb7cf65112cec589fca5f4647a6e56c13d5a8b0f has inconsistent version: filename has '0.6.3', but metadata has '-0.6.3-'
  Using cached pyturf-0.6.2.tar.gz (36 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Traceback (most recent call last):
        File "C:\Users\csmith\AppData\Local\Temp\pip-install-crdib7ap\pyturf_2416e4efeb4a4dafb55a094c3c1fd80b\setup.py", line 8, in <module>
          __version__ = os.environ["GITHUB_REF"].split("/")[-1]
        File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\os.py", line 680, in __getitem__
          raise KeyError(key) from None
      KeyError: 'GITHUB_REF'

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\csmith\AppData\Local\Temp\pip-install-crdib7ap\pyturf_2416e4efeb4a4dafb55a094c3c1fd80b\setup.py", line 11, in <module>
          from turf.version import __version__
        File "C:\Users\csmith\AppData\Local\Temp\pip-install-crdib7ap\pyturf_2416e4efeb4a4dafb55a094c3c1fd80b\turf\__init__.py", line 6, in <module>
          from turf.boolean_disjoint import boolean_disjoint
        File "C:\Users\csmith\AppData\Local\Temp\pip-install-crdib7ap\pyturf_2416e4efeb4a4dafb55a094c3c1fd80b\turf\boolean_disjoint\__init__.py", line 1, in <module>
          from turf.boolean_disjoint._boolean_disjoint import boolean_disjoint
        File "C:\Users\csmith\AppData\Local\Temp\pip-install-crdib7ap\pyturf_2416e4efeb4a4dafb55a094c3c1fd80b\turf\boolean_disjoint\_boolean_disjoint.py", line 18, in <module>
          from turf.line_intersect import line_intersect
        File "C:\Users\csmith\AppData\Local\Temp\pip-install-crdib7ap\pyturf_2416e4efeb4a4dafb55a094c3c1fd80b\turf\line_intersect\__init__.py", line 1, in <module>
          from turf.line_intersect._line_intersect import line_intersect
        File "C:\Users\csmith\AppData\Local\Temp\pip-install-crdib7ap\pyturf_2416e4efeb4a4dafb55a094c3c1fd80b\turf\line_intersect\_line_intersect.py", line 4, in <module>
          from rtree import index
      ModuleNotFoundError: No module named 'rtree'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```
@diogomatoschaves You're listed as the maintainer on PyPi, any chance you know how to fix this? Would love to give the package a try!

**Comment by SteffenHaeussler** [comment]
@traitortots the module rtree is missing. You can fix this with

`pip install rtree`

@jeafreezy I will have a look

**Comment by jeafreezy** [comment]
https://github.com/pyturf/pyturf/blob/cc899026aef38183f6043ea9957a72c9b8c87086/setup.py

I'm thinking it might have something to do with the environment variable.

**Comment by SteffenHaeussler** [comment]
@jeafreezy 

It seems that pip raises an error for v0.6.3 because there is an inconsistency between the filename (0.6.3) and the metadata (-0.6.3-). As a result, v0.6.2 will be installed, which fails with the error message above.

I know little about the pip packaging so I can fix this issue immediately.  I'm not sure, if I find enough time before the weekend. As a hotfix, I would recommend you this line in ubuntu:

`RUN pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver pyturf`

This should allow an installation and unblock you.

Here a dockerfile for testing:

```
FROM ubuntu:latest

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip

RUN pip install --upgrade --no-cache-dir --use-deprecated=legacy-resolver pyturf

ENTRYPOINT ["python3", "-c", "import turf; print(turf.__version__)"]
```

you should see the version number  with
`docker build -t test -f Dockerfile .`

and

`docker run test`

@traitortots It works with one install as you see in this example. It's just, that I need to figure out, how I can sync the metadata for the pip package.

**Comment by jeafreezy** [comment]
Thank you! Will give this go and let you know how it goes.

**Comment by SteffenHaeussler** [comment]
@jeafreezy @traitortots 

The installation issue is [fixed](https://github.com/pyturf/pyturf/pull/62) with v0.6.5.

Thanks for your help.
